version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-ghost-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-ghost-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-ghost-aarch64/
    schedule:
      interval: weekly